name: Custom Release Workflow

on:
  release:
    types:
      - created
  workflow_dispatch:

concurrency:
  group: release_workflow
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat .github/workflows/versions.env >> $GITHUB_ENV
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install curl clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev libjsoncpp-dev cmake-data libsecret-1-dev libsecret-1-0 librhash0 -y
      - run: flutter pub get
      - run: flutter build linux --release --target-platform linux-x64
      - name: Create archive
        run: tar -czf fluffychat-linux-x64.tar.gz -C build/linux/x64/release/bundle/ .
      - name: Upload archive as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

